name: Deploy

on:
  release:
    types: [published]

jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Set up git
        run: |
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'

      - name: Bump version to ${{ github.event.release.tag_name }}
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Push changes
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
